# Generated by Django 2.0.2 on 2019-05-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190520_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image02',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='image03',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='phrase02',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='phrase03',
            field=models.TextField(null=True),
        ),
    ]
